### ISSUE TITLE
[Opinion] Favor observer([stores], Component) over inject(store)

### ISSUE THREAD

**Issue by pavanpodila** [mobxjs/mobx-react#102]
When connecting stores, you have two options currently: 

- using `observer([stores], Component)`
- using `inject([stores])`

I actually prefer the `observer` and find it more convenient, and less error-prone compared to `inject`. The fact that you have to remember of order of usage:
- `inject` is the outer
- `observer` is the inner

...is easy to forget and a simple mistake can cause lot of pain debugging it. Just today I spent a few hours figuring out why my components were not reacting to store changes! And the issue was order of usage of `observer` and `inject`

I think constructs where you have to remember the order are easy to forget and sometimes very hard to debug. Of course now I have scars to remember for some time but for a newcomer that could be a painful realization :-(

I understand the idea that you want to keep the responsibilities separate

- inject to connect to stores
- observer to link React Components

but I think this is a case where these two responsibilities are so inter-connected that separating them makes adding caveats to their usage.

I am curious to hear what the maintainers think.

**Comment by zalmoxisus** [comment]
I was also thinking that it would be great to have an `injectAndObserve` decorator.

BTW, is it a good practice to have hundreds of `MobXStoreInjector` components? Or still better to keep them in the parent component?

**Comment by mweststrate** [comment]
@pavanpodila yep, using only one decorator is the most simple approach and also the one featured in the egghead course: https://egghead.io/lessons/react-mobx-fundamentals-connecting-components-to-stores-using-provider-and-observer

The separate decorator was only added later, the main reason being that there are some times third party decorators which should be applied in between, for example when using React-DND. Two separate decorators gives this flexibilility.

@zalmoxisus you mean instead of `observer([stores to inject], component)`? Personally I would only inject stores when jumping more then one level through the component tree (e.g. where you otherwise would need to pass them as props to a component that doesn't need the stores themselves). If parent and child both need the store, I would just pass it as props. Keeps the component tree cleaner as each inject HoC will create an additional component in the component tree.

**Comment by pavanpodila** [comment]
Ah that makes more sense now Michel

Thanks,
Pavan
