### ISSUE TITLE
@observer components does not update on context change

### ISSUE THREAD

**Issue by giladv** [mobxjs/mobx-react#104]
hi guys,
i lost a few hours on this - apparently @observer overrides the shouldComponentUpdate method
with a method which totally disregards context changes.
if it is a feature and not a bug, this should be written somewhere IMO.

why does is need to override the default method though? specially now when PureComponent was introduced...?

thanks,
Gilad

**Comment by andykog** [comment]
(related: https://github.com/facebook/react/issues/2517 )

**Comment by mweststrate** [comment]
@giladv is PureComponent afaik only a concept and not a thing? Note that the official PureRenderMixin also completely disregards context (as per https://github.com/facebook/react/blob/cba2b19b84b339e937b4bbc258cd09b2b8303391/src/addons/ReactComponentWithPureRenderMixin.js#L42). See also the thread @andykog mentioned

This issue in general is circumentvented by using a simple rule: context should be (shallowly) immutable. Meaning that you can safely push stores down the tree, but that you shouldn't replace them. Instead, stores should have the means to subscribe to them, for example by making them observable or by any other means.

Does that help? I'll doublecheck whether this strategy is sufficiently expressed in the docs.

**Comment by giladv** [comment]
@mweststrate it is new but it is an actual class. (e.g class Button extends PureComponent...)

specifically, i had a use case in which my Form component uses context to expose it's "FormStore" to child inputs to enable them to obtain values and such.
the problem started when switching between pages which in turn renders the same form with a different instance of "FormStore".

it is easily fixable thing, it just took me a while to understand that the context is not updating.
an update to the docs will be awesome in did:)

thanks!

**Comment by ronag** [comment]
> @giladv is PureComponent afaik only a concept and not a thing?

@mweststrate: It's part of React since 15.3

**Comment by kesha-antonov** [comment]
Hello guys!
Any updates on this?

**Comment by mweststrate** [comment]
No this is working as 'intended'. Supporting active context changes breaks any `shouldComponentUpdate` optimization in MobX or other libraries. See also this [blog](https://medium.com/react-ecosystem/how-to-handle-react-context-a7592dfdcbc#.gm3hfdryq). You don't have to be constrained by this though; if you put observables in your component, sub components will still react to the changes (because observables don't need to be passed down through the tree). 

If you don't use observables, make sure that your context is always shallowly immutable, so that even if you don't pass a new context down, changes deep inside the context can be seen. When not using observables, you probably want to accompany these objects with an event emitter so that you can listen to these changes.

**Comment by kesha-antonov** [comment]
Ok, got it. Thanks for the reply @mweststrate

**Comment by mweststrate** [comment]
Wrote an extensive blog post about the issue (it isn't mobx specific) and how to deal with it: https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076#.gbx4t9eix
