### ISSUE TITLE
Fired render method if value has not change?

### ISSUE THREAD

**Issue by jmaguirrei** [mobxjs/mobx-react#106]
Hi, please take a look at this code:

```javascript

import React from 'react';
import { observable, action } from 'mobx';
import { observer } from 'mobx-react';


class Main extends React.Component {

  @observable number;

  @action updateNumber(num) {
    this.number = [
      { somefield: num },
      { somefield: num + 1 },
    ];
  }

  constructor() {
    super();
    setInterval(() => {
      let num = 1;
      this.updateNumber(num);
    }, 1000);
  }

  render() {

    if (this.number) {
      console.log('Rendered: ', this.number[1].somefield);
      return (
        <div>
          { this.number[1].somefield }
        </div>
      );
    }

    return false;

  }

}

export default observer(Main);
```

The console shows that the same number is rendered every time.

![screenshot from 2016-08-21 12-49-31](https://cloud.githubusercontent.com/assets/11958637/17838212/efe52aae-679d-11e6-8cd9-cbf321ac7ae4.png)

So, I wish if it's possible to prevent this because in a large app this could be expensive.

Thanks

**Comment by mweststrate** [comment]
The problem here is that in your example you do change the number field every time; you give it a new array with new objects. (In other words, `var a = this.number; this.updateNumber(1); this.number !== a`). If you would change your code to `this.number[0].somefield = 1` it would behave as expected.

If you want you can ask MobX to do a deepEquality / structural equality check before seeing something as a change by using `@observable number = asStructure([])`. But note that can be potentially expensive for complicated objects

**Comment by jmaguirrei** [comment]
@mwestrate Thanks, I am wondering if the asStructure comparison for complicated objects has the same cost of lodash isEqual?

**Comment by jmaguirrei** [comment]
@andykog Thanks for the tip. I will go with asStructure for now and see how it goes.
