### ISSUE TITLE
Observe specific store properties

### ISSUE THREAD

**Issue by alolis** [mobxjs/mobx-react#126]
Hello,

I couldn't find anything in the docs here so I thought to ask. Is it possible to pass to the `@observer` component decorator specific store properties that someone wants to observe instead of the whole store?

There is something related here:
https://mobxjs.github.io/mobx/refguide/observe.html

> Usage: observe(target, propertyName?, listener, invokeImmediately?)
> 
> propertyName: optional parameter to specify a specific property to observe. Note that 
> observe(user.name, listener) is fundamentally different from observe(user, "name", listener). The > first observes the current value inside user.name (which might not be an observable at all), the 
> latter observes the name property of user.

It only supports one property though. 

Thank you for your time

**Comment by andykog** [comment]
@alolis, no, thats not possible. `observer` and `observe` are completely unrelated things.

**Comment by alolis** [comment]
@andykog , thanks for getting back to me. Would it be possible with some other way?

**Comment by andykog** [comment]
@alolis, why do you need it? It is possible with manual calling `this.setState` or `this.forceUpdate` inside autorun or reaction. Or making your own observer decorator, its quire simple https://github.com/mobxjs/mobx-react/blob/master/src/observer.js

**Comment by alolis** [comment]
@andykog , the reason is quite simple actually. For example I have a UIStore that stores everything related with the user interface of my app. The thing is that each component does not care for the whole store but only a few properties from it, so, in order to not pass the whole thing to each component, it would be nice to be able to pass only what each component needs making the code cleaner.

I will check out `observer.js` as well.

**Comment by mattruby** [comment]
Sounds like a good case for Provider.

**Comment by alolis** [comment]
@mattruby , if you make the change to the provider then all the components under the provider will be limited to that property only. The only way to make this work is if each component can observe, independently, different properties of the store. For example:

```
@observer(['UIStore.isSelected'])
class FooComponent extends React.Component {
   // component code
}

@observer(['UIStore.someProperty'])
class BarComponent extends React.Component {
   // component code
}
```

Adding this functionality to a Provider will not help at all.

**Comment by andykog** [comment]
@alolis, for me this sounds more suitable for custom `@propsSanitizers` decorator, separate from mobx-react.

**Comment by mweststrate** [comment]
@akolis It is not entirely clear for me whether you want to hide the properties for 1) protection, or 2) to prevent that components react to unrelevant properties?

For the first:
We actually do similar things quite frequently, but we are using typescript, so then it is quite easy to protected property access at runtime, just define an interface that exposes a subset of the properties, and use that interface in the property typings of the component. 

For the second:
`observer` only reacts to properties actually accessed in the last `render()`, it doesn't matter how many other properties there are in your store, the component won't react (nor even observe) them, so there is  no runtime penalty for having large versus small stores.

Finally, if you really want to expose only a small part of your stores, you could create a delegating object with just the properties you want, all declaring them computed, and redirect to the original model, e.g.:

```javascript
const user = observable({
  firstname: "michel",
  lastname: "weststrate"
})

function createSmallUser(user) {
   return observable({
     get firstname() {
        return user.firstname
     })
  })
}

const miniUser = createSmallUser(user)
```

I hope that helps! (otherwise feel free to re-open)
