### ISSUE TITLE
why published package does not have minified version?

### ISSUE THREAD

**Issue by marty-wang** [mobxjs/mobx-react#147]
npm module as well as CDN only have non-minified code. Why no minified version?

**Comment by mweststrate** [comment]
The majority of React projects bundle using webpack. Minifying after bundling your complete project usually gives a better developer experience.

**Comment by marty-wang** [comment]
I was hoping to use CDN for external libs, instead of bundling them with my app. but regardless, why not just minify it, and leave the developer to decide how to use it? I assume minification should be quite trivial.

**Comment by mweststrate** [comment]
@marty-wang I have no problem with adding that, it's just that so far nobody needed it. Seems CDN's are mostly interesting for PoCs and demo's, and less used for production apps.

Feel free to create a PR, or leave this issue open so that somebody else will pick it up :) Which flavors would be interesting for you, I assume only the default HTML renderer is interesting?

**Comment by marty-wang** [comment]
yes. only html renderer should be fine. Thanks.

**Comment by mweststrate** [comment]
This change can be tested with  `mobx-react@4.0.0-rc.1`
