### ISSUE TITLE
Sub-Provider store as computed value throws Warning

### ISSUE THREAD

**Issue by dropfen** [mobxjs/mobx-react#182]
Our structure looks like this:

Very small pseudo example

```
<Provider storeOne={storeOne}>
  <Router>
    <Route 
       path="/some/:id"
       onEnter={(paramsId) => { storeOne.setId(paramsId)} } component={Component} 
    />
  </Router>
</Provider>
```

storeOne has a computed value, based on the current Id

```
class storeOne {
   @observable id;
   items = [];
   @action setId(id) => this.id = id;
   @computed get current() => this.items[this.id];
}
```

in Component render we use the relative item of the store which is a computed value

```
<Provider item={storeOne.current} />
   <ItemConsumerOne />
   <ItemConsumerTwo />
   <ItemConsumerThree />
<Provider>
```

The problem now is, that every time we change the url, we see that warning:

https://github.com/mobxjs/mobx-react/blob/master/src/Provider.js#L41

What's the point of it? How could we suppress it, or do you see the critical points, we are not aware of? thank you!

**Comment by mweststrate** [comment]
The reason for the warning is that replacing a store is a change that might not make it to all descendents, if there is any `shouldComponentUpdate` in between that update might never arrive. (see https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076L for the reasons why). This could theoretically solved in mobx-react, but I think the proper way to think about `Provider` is as _dependency injection_, which as a thing that happens once. 

A simple workaround is probably to inject your store instead of item (possibly by using `@inject(stores => ({ item: stores.storeOne.current }))` if you don't want to be aware of `storeOne` in your component itself

**Comment by dropfen** [comment]
Thank you for the fast reply, it makes sense. However in our scenario we are aware what we are doing, some of us said we should suppress the warning explicitly if possible ;)

**Comment by dropfen** [comment]
Would you accept a pr like `if props.suppressChangedStoreWarning => no warning` ?

**Comment by mweststrate** [comment]
yeah that sounds reasonable :)

**Comment by dropfen** [comment]
is coming ;)

**Comment by dropfen** [comment]
@mweststrate the Link in your comment did't work

**Comment by mweststrate** [comment]
Thanks! Released as 4.0.4

**Comment by dropfen** [comment]
Great, thank you!

**Comment by alisabzevari** [comment]
What is the best practice of initializing a store based on another one and put both of them in `Provider`?
I have a store called `AuthManager` it owns an observeable property called `user`. Also I have another store called `GoalManager`. I need the `user` property of `AuthManager` to initialize `GoalManager`.
I want to construct `GoalManager` like this:
``` js
const goalManager = new GoalManager(user);
```
But it is not possible to instantiate a context property later!
I solved this problem by sending `AuthManager` instance to `GoalManager`'s constructor, but I don't like it:
``` js
// services.js

const authManager = new AuthManager();
const goalManager = new GoalManager(authManager);

export default {
  authManager,
  goalManager
}
```
and later:
``` js
// index.jsx

import services from './services';

render(`
  <Provider {...services}>
    <App />
  </Provider>`, mountPoint);
```
I don't like this solution because I had to depend `GoalManager` to `AuthManager` but it only depends on `AuthManager.user`. Then testing `GoalManager` is  harder (because you have to mock a big object).

Is there any better solution for that?

**PS:** Another (probably stupid) question is that why `@inject` needs to use react context as a dependency container. It can depend on the real instance! like this:
``` js
// MyComponent.js

import { authManager } from './services';

const MyComponent = ...

export default inject({ authManager })(MyComponent);
```

**Comment by dropfen** [comment]
@alisabzevari This is a **How-To Question**, not really related to mobx generally, but your special Data-Model design, I think its better to open a stackoverflow question for this. feel free to copy the stackoverflow link here.

**Comment by alisabzevari** [comment]
@dropfen I asked two questions in SO:
* [How to add stores to mobx-react Provider when they are dependent to each other?](http://stackoverflow.com/questions/41480431/how-to-add-stores-to-mobx-react-provider-when-they-are-dependent-to-each-other)
* [Why mobx inject needs to use react's context?](http://stackoverflow.com/questions/41480341/why-mobx-inject-needs-to-use-reacts-context)
