### ISSUE TITLE
Computed ordering issue

### ISSUE THREAD

**Issue by JakeCoxon** [mobxjs/mobx-react#199]
I have a fiddle here https://jsfiddle.net/p5u1u9rt/

Todos renders TodoView when there are todos, and correctly unmounts the child when there are none, unfortunately the computed on the TodoView is still recalculated after the list is cleared.

I would like to make the assumption in TodoView that its lifecycle is valid only while there are todos in the list, otherwise I have to do a lot of unnecessary checks in every computed.

It's a bigger problem where I'm using mobx 2 because it throws exceptions. 

I'd like to investigate this myself but I don't know where I'd start. Thanks for your time

**Comment by mweststrate** [comment]
The problem you are running into is that react doesn't order the rendering of parents before child when not inside a react batch. I think your problem is fixed if you wrap your code in `React.unstableBatchedUpdates(() => { /* create and remove todos here */ }`

However, if you use the latest mobx / mobx-react versions, this batching is automatically done for you if you modify the state inside a MobX action. (You can enable MobX strict mode to enforce this). Note that react itself also automatically applies this batching if you change state in an event handler for example. The reason it isn't working for you and the child / parent are rendered in the wrong order, is the fact that the two statements happen in 'top level' code react has no contorl over.

That explains the problem :) But I think in your situation you can simply fix the issue by not passing an index to the `TodoView` component, but the todo itself instead. This makes the code both cleaner / clearer to follow, it and will scale much better performance wise, as with your current approach the VDOM cannot optimize the insertion of new todos (every component after the inserted one would receive a new index and need to be re-rendered again, while if using a key and passing the todo object in, only the inserted component needs a re-render)

It also fixes your problem, as the componentView will no longer react to the array, but only to it's todo item, regardless whether it is still in the array or not. (The parent will still make sure the componentView is properly unmounted, but the order in which this happen will no longer influence the behavior of your app)

Hope that helps!

**Comment by JakeCoxon** [comment]
Thanks for getting back to me :)

I think the problem isn't react render ordering because the *render* is not running after the todo is removed - only the computed function.

> That explains the problem :) But I think in your situation you can simply fix the issue by not passing an index to the TodoView component, but the todo itself instead

> It also fixes your problem, as the componentView will no longer react to the array, but only to it's todo item, regardless whether it is still in the array or not.

In general I would agree, it was a simplification of the real issue to demonstrate that the data is invalid at the point of calculation. My real issue comes when using mobx-state-tree, and when a node is detached from the tree, its data is all sorts of invalid (I use getParent quite a bit). It's possible for me to check everywhere that the node is not detatched, but it's proving quite error prone.

I think it's not a problem with mobx-state-tree but with mobx-react since the component is not being re-rendered, but the computed is still triggering. Intuitively I would think that computed would stop being listened to when the component is unmounted. Could it be a bug in the execution ordering? Or have I got something wrong? :D

I've updated the fiddle to use event handlers and mobx actions, just in case. I'm also simulating the todo being detatched with an observable isDetatched value, once it is detatched I basically never want to render it. You can see after you click it, the render function is not called but the `@computed get text` is called with some invalid state

https://jsfiddle.net/p5u1u9rt/1/

**Comment by mweststrate** [comment]
I think this situation is not entirely avoidable, all the computeds run before all the components, to make sure the components see the correct data, so the computeds cannot calculate in the fact that the component that is observing them won't need to render anymore. For the cases where this could be an issue I think we cannot do better than write a sanity check there. Or to put it differently: any computed value should produce a sane value until it is GC-ed, regardless whether it is still observed or not.
