### ISSUE TITLE
Cannot mark an arrow function as an @action

### ISSUE THREAD

**Issue by scriby** [mobxjs/mobx-react#200]
A common pattern for action handlers in ES6 is to bind them to the class:

```
  @action
  handleClick = () => {
    //"this" works here
  }
```

However, the `@action` decorator doesn't seem to be able to be applied to an arrow function like that.

It would be nice if that worked. Is there another recommendation?

**Comment by mweststrate** [comment]
That should actually just work as expected. Do you have an more elaborate
example?

Op di 31 jan. 2017 22:29 schreef scriby <notifications@github.com>:

**Comment by scriby** [comment]
Probably the reason it doesn't work is b/c I am working in typescript which is setup to emit ES5, so the function declaration ends up getting put in the constructor in such a way the decorator can no longer apply itself.

I worked around it by doing it like this:

```
handleClick = action(() => {

})
```

What do you think of that approach?

**Comment by mweststrate** [comment]
The work around is perfectly fine, but the original approach should work as
well, we do the same think in typescript, targeting ES5. Enabled
experimentalDecorators? Are you using React with React hot loader? Note
that Only the latest beta of React hot-loader supports decorators.
Otherwise, could you create a small reproduction?

Op di 31 jan. 2017 om 23:38 schreef scriby <notifications@github.com>:

**Comment by scriby** [comment]
We are using the react hot loader, perhaps that is the issue. I can post a stack trace tomorrow.

**Comment by scriby** [comment]
I took a look at the stack trace and it is indeed coming from hot module loading. I'll go ahead and close this.
