### ISSUE TITLE
Allow a way to opt-out of state and props being observables

### ISSUE THREAD

**Issue by liady** [mobxjs/mobx-react#246]
In v4 there was a change causing `state` and `props` to be observables as well (#124).
Will it cause an overhead when updating state/props?
Can you provide a way to opt-out of this behavior (perhaps passing an options object to `@observer`)?

**Comment by mweststrate** [comment]
Technically it could be done, but unless there is a clear use case or hard performance numbers of a real life use case, I don't see any reason to do so. As it only increases the api complexity and will result in difficult to answer issues because of the subtle semantically differences if this option would be enabled.

**Comment by liady** [comment]
@mwestrate thanks for the response.
Currently we're using mobx-react with react-css-modules, which in tandem cause an infinite render loop. 
For now we created a fork of our own, without the new observable functionality, but it would be great if the library itself could support it.

**Comment by mweststrate** [comment]
@liady could you set up a small repo demonstrating the problem? I want to investigate whether there are less radical solutions :)

**Comment by henrify** [comment]
@mweststrate We are currently evaluating mobx, and immediately after enabling 'observable' decorators noticed performance slowdown in some components.

I traced the issue to slower access of this.state and this.props caused by Atom.reportObserved().

The slowdown is significant (5-10%} in components that render continuously. Worst case is table with 70 visible rows, 10 columns, rendering at 60fps during scrolling, and each render does 6 props/state accesses. That's quarter of million reportObserved() calls per second...

Here are reasons why you should implement the requested option to observable:

1. If @liady has already run into infinite render loop, others are going to be hit by it sooner or later. Requiring users to work-around on case-by-case basis, even doing custom builds, doesn't sound optimal.

2. We run into the above performance problem 'in the wild', and again, sooner or later also others will run into it. In rare cases it can be significant, but more commonly there is going to be constant 'tax' to performance, which is often completely unnecessary.

3. Semantically it is completely non obvious that by making component observER, it also turns parts of itself as observABLE. I also didn't notice it in the docs (?).

4. By far the most common reason why people don't use mobx seems to be that it is perceived as "too magical". Having a feature that is non-obvious and can cause infinite render loops and performance issues, but cannot be turned off, is another hit to the 'too magical' direction.

5. In terms of API, adding modifiers to observable would be completely consistent with other parts of API, and the implementation should be simple.

Are there any objections why this should not be added?

**Comment by mweststrate** [comment]
@henrify I think this is indeed one of the most disputable features in mobx-react. I don't like it at all as it hooks into react internals where it shouldn't. It was introduced for one simple reason only:

```javascript
@observer class User extends Component {
   @computed get fullName() {
       return this.props.user.firstName + this.props.user.lastName
   }

   render() {
       <div>{this.fullname}: { this.props.user.age }</div>
   }
}
``` 

The reason why props (and state) are made observable are simply this. If they aren't, passing a new `user` to the component instance will update the age but not the name. And even though that is strictly speaking behaving correct, it is really unobvious that that would happen, and I don't see a clean way around that yet.

**Comment by delight-by** [comment]
I was very surprised by that change in v4 too. That just doesn't feel right and I couldn't make myself to sympathize to any of 3 examples here and in #124.
@mweststrate Re your code above - why would anyone make fullName computed in the first place? What's the reasoning behind it? Do I understand correctly that if you drop computed here, you'll get 1) re-renders when observed user changes thanks to mobx and calling fullName inside render and 2) re-renders when props change thanks to react. So isn't that an expected behavior? What am I missing?
As for use cases in #124 - they look too artificial for me, more like "I don't like componentWillReceiveProps, let's make props observable". And are probably better accomodated with another wrapper/decorator.

**Comment by mweststrate** [comment]
@delight-by that `fullName` is computed in the above is of course a contrived example, but it demonstrates the underlying issue: if the component receives new props from it's parent, this is not reflected in any computed property declared on the component; they won't recalculate accordingly, because if `this.props.user`  reference changes; this change is not observable, so the computed value won't be notified and keep returning it's old value

**Comment by delight-by** [comment]
@mweststrate I understand the problem but I still don't understand the reasoning behind declaring a computed property on a component. If you're going to use it in render - then just remove computed and it should work as expected. Using computed property outside of render? Well... ok, but that's something not everyone would do and it's better to have it as an opt-in.

**Comment by AlexGalays** [comment]
@delight-by On a performance level, the case for computed values inside a React component is exactly the same as in Data/Stores: It won't reevaluate its body if none of its dependencies changed, trading memory for cpu.

Recalculating everything in render is the traditional and slow React way (though it's fast enough for most apps) but one could argue that mobx already optimizing the number of times render() will be called makes this strategy good enough, and we're only talking about non domain observables here as those should likely be in the data/stores in the first place.

I didn't use the lib enough to know which mode is the best but opt-out switches or having many ways to do the same thing are annoying (there's already strict mode, etc or decorators that don't work with TS, etc) and make the documentation harder to read. I would prefer if this lib made clear compromises and aggressively removed useless features :)

Compiling a list of what it allows one to do could help deciding.

**Comment by FredyC** [comment]
Closing as stale.
