### ISSUE TITLE
Is there any difference without using `Provider` and `inject` ?

### ISSUE THREAD

**Issue by varHarrie** [mobxjs/mobx-react#327]
I have following questions when using `mobx-react`:

```typescript
// ProjectStore.ts
import {observable} from 'mobx'

export default class ProjectStore {
  @observable
  projects: any[] = []
}

// stores.ts
import ProjectStore from './ProjectStore'

export const projectStore  = new ProjectStore()

// App.tsx
import * as React from 'react'
import {observer} from 'mobx-react'
import {projectStore} from './stores'

@observer  // ---------------> still work? or no need?
export default class Appextends React.Component {

  render () {
    const {projects} = projectStore

    return (
      <div>
        <ul>
          {projects.map((project) => (
            <li key={project.id}>{project.title}</li>
          ))}
        </ul>
      </div>
    )
  }
}
```
- Question 1: `@observer` still work? or no need?

- Question 2: What is the difference from using `Provider` and `@inject`, or any impact performance?

**Comment by urugator** [comment]
`@observer` is always required, otherwise the component has no means to react to observables. It must be applied first - before `@inject` - like this `@inject("something") @observer class Component {}`.

`Provider` is used to put *things* (dependencis) on react's context. The context is available to all descendant components. The *things* are identified by name: `<Provider name={thing}>`.

`@inject` is used to retrieve these *things* from context in descendants of `Provider`. Inject takes these things from context by name and makes them available by moving them to props with the same name.
So `inject("name")` will take "name" *thing* from the context and make it available as `this.props.name`

Performance impact is negligible.

**Comment by varHarrie** [comment]
@urugator Thank for your reply.

According to your answer, `Provider` and `@inject` is one of ways to pass store into components, but not neccessary. And I also can directly `require` or `import` store instance from another file, There's no essential difference. Right?

**Comment by urugator** [comment]
> Provider and @inject is one of ways to pass store into components, but not neccessary

Yes

> And I also can directly require or import store instance from another file

Yes, but it makes SSR and testing problematic. I consider using module cache as a data storage as a misuse in general.

**Comment by jmaguirrei** [comment]
@urugator 

> Yes, but it makes SSR and testing problematic. I consider using module cache as a data storage a misuse in general.

Let's say the are 2 different patterns:

- Pattern A: Store(s) => Component => Subcomponent => SubComp ...
- Pattern B: Store(s) => Provider => Component => Subcomponent => (inject) => SubComp...

I understand that Provider also needs to import the stores the component needs from another files, before passing it to the components, dont?

So, how is the Provider pattern better?

I am wondering if a refactoring is needed to my code (Pattern A), so this could help me understand better,

Thanks

**Comment by mweststrate** [comment]
I think with a little searching you can find other issues in this or the
mobx repo discussing the pro's and con's of either approaches

Op do 21 sep. 2017 om 14:16 schreef José Manuel Aguirre <
notifications@github.com>:

**Comment by urugator** [comment]
> I understand that Provider also needs to import the stores the component needs from another files

Yea, but you will import only the store **definition** (class), not an **instance**. The instance itself is created in some component and passed to Provider, making this particular instance available to a certain subtree of components.
Therefore you can have multiple instances of the same store inside your application (which is required for SSR, because you have multiple requests and each needs own set of stores) or even in component tree (stores don't have to be singletons).
Normally you would pass the instance via props down the component tree. By passing the store via props, the store and props are decoupled and easily testable.
The only problem are transitive dependencies, where some components in the hierarchy don't depend on some stores, but their children are, so they have to *pass through* these deps down to the children.
To overcome this you can use react's context. But then your component depends on context. This can be solved by moving this context dependency to HOC. And that's exactly what `@inject` does - it transforms context deps to props deps.
So with `@inject` you can design the component like it would use props to pass it's dependencies, while avoiding the problem with transitive dependencies.

**Comment by jmaguirrei** [comment]
@urugator thanks for the explanation!

To be honest, it's first time I read that stores cannot be singleton.
I understand about SSR having different routes, different stores instances, because one doesnt know about the other.

But in a single page app, client side only, having 2 or more instances of the same store seems unnatural to me, because they may differ after user actions (but off course they should sync with same backend to consolidate new data). Also I may be using more resources because of duplication ?

To make my point, if the following:
- No SSR, client side only
- Single page app and single instance of each store
- One context object that holds all stores in one place (just for convenience when passing to parent components).
- Passing required stores down to the component tree (dereference values when they need to be used).
- Test passing mocked context object to parents.

In this scenario, what are still the advantages of Provider/multiple instances pattern?

**Comment by urugator** [comment]
> it's first time I read that stores cannot be singleton

I haven't said that. There is a difference between singleton and the way it's implemented.
The singleton is single inside a certain scope. The problem is that with module cache, you're unable to control this scope.
What is the scope of the application?
Intrepret/sandbox/globals/request/VM/container/thread/context/component/unit test/tenant/node/cluster? And why your class/module/function should care about that, it's not it's concern.  
The scope of things always depends on usage, so it should be controlled by consumer.    

> because they may differ after user action

Which is sometimes the point. You may have a store which represents a list item. Then you need ItemStore instance for each item. Or perhaps you have multiple lists etc...
Again, it's not a concern of the item or the list, whether they will be single or not.
(Note that Mobx "store" doesn't have to fit in flux's "store" definition)

Just to make things clear, Provider doesn't relate to instances or to imports/modules, it relates to passing (any) things via contex/props (instance/declaration/value/whatever).
You should use Provider/inject if you have problems with passing things by props. The singleton implemented as module is a different problem.
It's just that you may not see the need for Povider/inject, if you use module cache as a context to pass deps.
And note that Provider/inject isn't the only solution.

**Comment by jmaguirrei** [comment]
Thanks @urugator I learn something new today 👍 

I guess both patterns are valid, and Provider/inject is more a convenience for the programmer to use the context instead of passing props many levels.

My plan is to have only one module importing all stores (the context object) and then pass that object explicitly to all parents components, which then acts as providers to all its descendants.

I took the idea from this:
https://kadirahq.github.io/mantra/#sec-Application-Context

**Comment by varHarrie** [comment]
All is clear, thank you.

**Comment by DominikSerafin** [comment]
This single comment should be on top of the readme
 https://github.com/mobxjs/mobx-react/issues/327#issuecomment-330854616

Thanks @urugator

**Comment by mweststrate** [comment]
Feel free to PR! it is a super useful comment :)

Op do 7 jun. 2018 om 16:13 schreef Dominik Serafin <notifications@github.com
