### ISSUE TITLE
[question] Performance gain: observe vs observer

### ISSUE THREAD

**Issue by kesha-antonov** [mobxjs/mobx-react#346]
Hello! 

Is there performance gain to use ```observe``` instead ```observer```?

I can set ```observer``` on class and forget about it or can use ```observe``` to some specific fields. Which is better/faster?

My main ```store``` has refs to other ```stores```

And what advices you can give about mobx - how to speed up app?

Thanks!

**Comment by mweststrate** [comment]
I generally avoid `observe`, it doesn't support batching or transaction, or transparent tracking, so using it a lot will probably slow things down. Beyond that enable strictMode to be forced to use actions and read the performance tips in the docs https://mobx.js.org/best/react-performance.html.

But the best performance tip as usual is: don't do premature optimization. It will make things worse instead of better. First measure and identify performance bottlenecks. Otherwise you are just screwing up you code in vain. Like doing a lot of boilerplate work by using `observe` instead of `observer` without knowing it will make things better instead of worse.

**Comment by kesha-antonov** [comment]
Good point! Thanks! Measure before doing work.
