### ISSUE TITLE
TypeScript regression: "Property 'displayName' does not exist on type ..."

### ISSUE THREAD

**Issue by tkrotoff** [mobxjs/mobx-react#352]
Since v4.3.4, commit https://github.com/mobxjs/mobx-react/commit/f478d5e77203c8ad4516bfe17ab6e2c5ec422466 introduced a regression:

```TypeScript
const FooBar = observer(() => <div />);
FooBar.displayName = 'FooBar';
```

Error:
```
[ts] Property 'displayName' does not exist on type '() => Element'.
```

This is because now `observer` is defined as:
```TypeScript
export function observer<T extends IReactComponent>(
    target: T
): T
```
and does not return `React.ClassicComponentClass<P>` as before: https://github.com/mobxjs/mobx-react/blob/4.3.3/src/index.d.ts#L26

Writing `FooBar.displayName = 'FooBar'` is important otherwise you get `_class` in React DevTools instead of `FooBar`, see https://github.com/mobxjs/mobx-react/pull/340#issuecomment-341664886

From my tests, it seems this is more a react.d.ts problem:
```TypeScript
const FooBar1 = observer(() => <div />);
FooBar1.displayName = 'FooBar'; // Error

const FooBar2 = () => <div />;
FooBar2.displayName = 'FooBar'; // Error

const FooBar3: React.SFC = () => <div />;
FooBar3.displayName = 'FooBar';

const FooBar4 = observer(() => <div />) as React.SFC;
FooBar4.displayName = 'FooBar';
```

vscode screenshot:
![screen shot 2017-11-03 at 11 28 01](https://user-images.githubusercontent.com/643434/32369940-84d24204-c08b-11e7-83c2-30ad6e336acb.png)

Even if its a react.d.ts issue, I wanted you opinion on it (is the `as React.SFC` cast legit and wanted?).
Thx in advance

**Comment by mweststrate** [comment]
I  did a 1 minute search but couldn't really find that `displayName` is actually a feature of SDFc's, I think they are supposed to be used like `const FooBar1 = observer(function Foobar () { return <div /> });` if you want to name them?

Anyway I think it is a useful feature but should be fixed primarily in the react typings I think. I think the new typings are neater then they were since they return the type that you passed in, instead of always returning a ClassicComponent. The current typings are neater I think

**Comment by tkrotoff** [comment]
Thx for you reply.
`const FooBar1 = observer(function Foobar () { return <div /> })`: this works.

In the end I prefer writing `(Foobar as React.SFC).displayName = 'Foobar'` => more explicit.
