### ISSUE TITLE
Destructuring the store

### ISSUE THREAD

**Issue by neurosnap** [mobxjs/mobx-react#36]
Are there any issues with doing something like this:

```
import React from 'react';
import { render } from 'react-dom';
import { observer } from 'react-redux';
import { store } from './store';

const App = observer(({ threads }) => (<div>{threads.map(thread => <div>{thread.name}</div>)}</div>);
render(<App {...store} />, document.getElementById('app'));
```

**Comment by mweststrate** [comment]
Yes, I recommend not doing this. There are few issues with this pattern:

1. computed properties won't be passed as those are non-enumerable
2. When using classes; I'm not sure whether prototype properties are passed, I think only the own properies are passed by the spread operator.
3. If your store contains primitive values, only the values will be passed, not the observable properties themselves. For example if you spread a value like `store = observable({x:3})`, and spread the store, only  the current value of `x`, namely `3`, will be passed to the component. Because de-structuring just takes the current values, and not the observable _properties_, so `App` won't be notified for new values of `x`
