### ISSUE TITLE
Question: Best practice to use @inject

### ISSUE THREAD

**Issue by xuchaobei** [mobxjs/mobx-react#361]
I know using `@observer` on more small components is good for the performance. Is it also reasonable to use `@inject` on as many as possible components ? Obviously, in this way it is easier to access the used props than passing through parent components. At the same time,  it also becomes difficult to create presentational components. Nearly all components are directly connected to Mobx's stores. But even if we don't use `@inject`, the component may still use `@observer`.

So my questions are:
1. How to create presentational components in Mobx? Or maybe there is no need for presentational components in Mobx. 
2. What is the best practice to use `@inject` ? Or which components are reasonable to used with `@inject`?

**Comment by urugator** [comment]
> How to create presentational components in Mobx? Or maybe there is no need for presentational components in Mobx.

I would say it's exactly the opposite - there is almost no need for "container" components, because all the logic can be placed in "stores". So most of the components are simple renderers and can be considered "presentational".

> What is the best practice to use @inject? Or which components are reasonable to used with @inject?

Note that `@inject` also accepts a (reactive) mapper function, which allows your components to be completely independent of context and can rely on props alone. 

The biggest issue with `@inject` is that it uses a context - a single global namespace available to any component. I suggest to not overusing it and try to go with normal component composition first.
To avoid the need for passing props through mutliple levels (transitive deps), pass render callbacks as props whenever possible (whenever a component is not a leaf).

**Comment by xuchaobei** [comment]
@urugator thanks. I am not very clear about 
> pass render callbacks as props whenever possible 
 
Could you give an example code ?

**Comment by urugator** [comment]
Please use the google for the term "render callback", there is a plenty of articles about it.
