### ISSUE TITLE
Does mobx react to this?

### ISSUE THREAD

**Issue by giorgim** [mobxjs/mobx-react#362]
Imagine I have object

```

let message = {
    title: "Foo",
    author: {
        name: "Michel"
    },
    likes: [
        "John", "Sara"
    ]
}
```

And _observable_ array of `message ` like objects. Imagine I passed each object from that array as a prop to a component. When the component changed the prop from within, a re-render was not being called, e.g.

```
render(){
...
this.messages.map(function (item) {
            return <TodoItem message = {item}/>
        });
```

Now, if I changed a property of `message ` from `TodoItem`:

`this.props.message.title="hi"
`

the original render above (the one which rendered `TodoItems`) would not be called again. Why?

**Comment by giorgim** [comment]
I think I resolved what was going on.

it was related to the fact that inside `TodoItem `I was making a copy of `title `property in constructor e.g.
`this.value = this.props.message.title;`

and using above value as value of text field. Then inside `TodoItem ` I had button, when user clicked this button, I would set indeed

`this.props.message.title="hi";`

but this was not tracked anymore due to two reasons:

- The parent component which rendered `TodoItem ` wasn't interested in this change (apparently), because in its method I was just using `{item}`
- due to copy made now also the child `TodoItem` didn't track this change because eveywhere in render of `TodoItem `item I was using `this.value `now

**Comment by urugator** [comment]
Can't tell for sure without seeing the whole sources, but yea it seems the problem was that you created a copy inside a constructor which runs "outside of tracking context". Only `render` function is tracked - component subscribes only to observables accessed inside `render`. (accessed observable is an observable you "dotted into", like: `item.title` or `boxed.get()`  ... MobX subscription logic is hidden inside getters) 
Note that storing a copy of props to local fields is generally bad idea (in React) - the constructor is called once at the component creation, so the assigment to `this.value` is also performed only once.
I don't suggest to do so, but computed would work:
```javascript
@computed get value() {
   return this.props.message.title;
   // the computed is now subscribed for this.props and message.title
   // (btw it's not subscribed for props.message, because props object itself is immutable, so it can't have observable fields)
}
// at this point this.value is observable and can be used in render
```

> And whether the situation I encountered there is something you were referring to in this post using:

In your situation the problem was mainly the copy.
I was reffering to the fact that if you would have `@observable value`, then you can pass it down only as a value and value cannot be "dotted into", therefore the children can't use MobX to react to value change. Nevertheless the child will be still updated together with parent by recieving new props.
To make the value "dottable", you have to wrap it into boxed observable/boxed computed/observable object - which is a form of abstraction ("a model")...

**Comment by giorgim** [comment]
@urugator Yeah and like I said parent component was not also reacting to (which was called inside `TodoItem`)

`this.props.message.title="hi"
`
because apparently in parent component I only have

```
this.messages.map(function (item) {
            return <TodoItem message = {item}/>
        });
```

Because if it had reacted then the child would have updated prop because I also had logic in `TodoItem ` `componentwillreceiveprops` to update the `this.value` using newprops.

**Comment by urugator** [comment]
Yes, the parent is subscribed only for `messages` (in case it's observable), because you've "dotted into" by `messages.map`, but not for anything inside `item`, like `item.title`.
