### ISSUE TITLE
Import a module which offers react component written with mobx-react.

### ISSUE THREAD

**Issue by breakds** [mobxjs/mobx-react#384]
Hi the mobx-react community! Happy Holidays!

I am working on a project that needs to use some component from another (local) module called `react-tile-map`. This module is added to my project with

```
yarn add file:/path/to/react-tile-map
```

When I try to import the component from it, my project panics about the decorators in `react-tile-map`:

```
../node_modules/react-tile-map/src/tile-map.js
Module parse failed: Unexpected character '@' (10:0)
You may need an appropriate loader to handle this file type.
| export * from "./state";
| 
| @observer
| export class TileMap extends React.Component {
|   static propTypes = {
```

My project has correct babel plugins to allow decorators:

```json
{
  "presets": [
    "react-app"
  ],
  "plugins": [
    "transform-decorators-legacy",
  ]
}
```

However, it seems that `babel-loader` is not applied on the files from `react-tile-map`.

Since I am new to javascript development, my questions might seem silly, which are:

1. Do I have to first transpile `react-tile-map` (so that decorators are gone) and load it? What is the best practice here?
2. Is there anyway I can import components from `react-tile-map` as is?

Thanks a lot!

**Comment by mweststrate** [comment]
Best practice is to always compile packages down to the most common thing
all consumers understand out of the box and without config. In general that
is commonjs + ES5. The mobx-react package itself is an example of that (see
the main field in the package.json). It also ships UMD and ESM builds, but
that is often not needed.

Op za 30 dec. 2017 om 19:05 schreef Break Yang <notifications@github.com>:

**Comment by breakds** [comment]
Thanks a lot for the prompt reply! I followed your advice and it solved the previous problem! 

I am now running into the problem of multiple mobx instances, but I think that is an unrelated problem :)

**Comment by urugator** [comment]
`node_modules` is probably excluded from transpilation, which is useful, because external dependencies are distributed already transpiled. Your local file is added to this folder and therefore excluded as well.

Some options:

1) Don't use yarn/npm to manage this dependency.
Copy the file/module manually and import it as local file using relative path.

2) Modify webpack configuration to include this file

3) Make the module "publicly usable" - so that it's already transpiled as @mweststrate suggested

4) If you want to manage local deps with yarn/npm you can structure your app like this:
```
ProjectFolder
  node_modules // contains external dependencies
  src
    node_modules // contains local dependencies
    index.js    
```
Keep the `ProjectFolder/node_modules` excluded from transpilation, but include the `ProjectFolder/src/node_models`. Import modules as you're used to. The module resolver first looks for dependency in `src/node_modules` and continues search in `ProjectFolder/node_modules` if not found.

**Comment by breakds** [comment]
@urugator Thanks for the suggestions. The problem is now solved by 

1. The shared module is still managed by `yarn`, but with

    ```json
      "main": "build/index.js",
    ```

    in `package.json` so that it offers already-transpiled files to the outside world.

2. The main project depends on the shard module by
    
    ```
    yarn add file:path/to/my/shared/module
    ```

The above two steps solved the problem (but not the duplicated mobx one, unfortunately).
