### ISSUE TITLE
Component mounted on each observable array mutation

### ISSUE THREAD

**Issue by rickmed** [mobxjs/mobx-react#39]
EDIT: nevermind, my mistake using key badly. Can be closed

**Comment by mweststrate** [comment]
Yes, since you use `Date.now()` as key :). components with the same key are
matched against each other, with different keys you always get different
components. If you would gave each card object an id field initialized with
query + Date.now() it would mostly work (you can stil have collisions).
Simplest solution is to give each card its own unique number by generating
an UUID or having a global counter or something like that

Op wo 13 apr. 2016 om 07:20 schreef rickmed <notifications@github.com>:

**Comment by rickmed** [comment]
@mweststrate yeap, silly mistakes like that makes you look elsewhere :). What do you mean by you can still have collisions?  (sorry I think this is off topic) In my specific case one user can't introduce an input exactly at the same time.

**Comment by mweststrate** [comment]
ok then it should work :)
