### ISSUE TITLE
Using observer() throws:  Argument of type 'typeof Foo' is not assignable to parameter of type 'IReactComponent<any>'. 

### ISSUE THREAD

**Issue by amrfarid140** [mobxjs/mobx-react#396]
I am trying to make a React component an observer. 

If I do it like that:

```
interface LoginViewProps{
    dataProvider:IDataProvider;
}

class LoginView extends React.Component<LoginViewProps,null>{
    
    viewModel: ILoginViewModel;
    constructor(props:LoginViewProps){
        super(props);
        this.viewModel = new LoginViewModel();
        this.viewModel.dataProvider = props.dataProvider
    }
}
export default observer(LoginView);
```

I get the following error:

`(19,25): Argument of type 'typeof LoginView' is not assignable to parameter of type 'IReactComponent<any>'.
  Type 'typeof LoginView' is not assignable to type 'ClassicComponentClass<any>'.
    Type 'LoginView' is not assignable to type 'ClassicComponent<any, ComponentState>'.
      Property 'replaceState' is missing in type 'LoginView'.`

But If I did the following I don't get an error:

`...
class LoginView extends React.Component {
...`

Is that normal ? How can I fix this ?

**Comment by amrfarid140** [comment]
The issue was my tsconfig.json file forcing some strict configuration. I will mark it as closed.

**Comment by rifler** [comment]
@amrfarid140 can you please provide a solution?

**Comment by vipseixas** [comment]
I am having this problem now and what is causing it is the presence of the componentDidUpdate life-cycle method. Just by commenting the method the error is gone.

Can this issue be reopened?

**Comment by mweststrate** [comment]
@vipseixas open a fresh issue including minimal reproduction

**Comment by vipseixas** [comment]
@mweststrate Just figured out what was happening, I'll leave the solution here for other people with the same problem:

My `componentDidUpdate` method was with a subtle error at its signature, instead of

`componentDidUpdate(prevProps: Props, prevState: State) { ... }`

It was:

`componentDidUpdate(prevProps: Props, prevState?: State) { ... }`

So the compiler made the component incompatible with the observer() parameters. 

I don't quite understand why the compiler did not complain about the method itself but complains about the component type afterwards but it seems that any change at the signatures of life-cycle methods causes this issue.
