### ISSUE TITLE
Cached React components not properly reacting to primitive observables

### ISSUE THREAD

**Issue by iabw** [mobxjs/mobx-react#433]
I apologize if this belongs in the main mobx repo, but I'm unclear if the problem I'm having is with the observer or observable decorator.

I have searched every permutation of "observer not updating", "cached components", etc and couldn't find any bug reports or documentation about what I'm seeing here.

Non-working example: https://jsfiddle.net/wv3yopo0/2694/
Working example: https://jsfiddle.net/wv3yopo0/2693/

In the first example, you can see that I'm updating this.counter directly, and only caching the items after the first one. You can see this.counter properly updating that first item, which is in-line with [how the observer decorator is documented](https://mobx.js.org/refguide/observer-component.html#observable-local-component-state). I also expected the other components being rendered into the cache to be updated, but they're not.

In the second example, I've wrapped this.counter's value in an object and the cached components are now properly updating (what I expected all along). The only difference from example 1 is the 3 lines that reference this.counter.counter.

Since uncached primitive and wrapping the counter both work, I suspect this is some kind of bug in the observer decorator's implementation of the "auto-boxing" that has to happen on primitive observables.

But maybe this is expected and I just misunderstood something about how the observer decorator decides to change when observables change (or missed something in the docs)?

**Comment by iabw** [comment]
Thanks for your response. Some great points, and I'm sorry if you feel these questions are covered by that page or in other documentation that I managed to miss. With those pointers, I've figured out what I need to do for the specific problem I had.

The simple counter was because I boiled down the repro too far. I adjusted it to have the same issue displayed closer to the real use-case - a computed list of visible columns for an observable list of rows - https://jsfiddle.net/wv3yopo0/2746/

I think I understand now that although the computed visibleColumns list in this example causes the TestListController to re-render every time it changes, it's then a vanilla array when TestListController passes it to the TestListRow, and so the cached TestListRow obviously doesn't pick up future updates. I had the mistaken idea that a computed property was somehow magically observable to deeply nested components as long as they got a reference. It seems like the correct way to do this is wrapping my array in an observable and explicitly setting it from the action that changes it - https://jsfiddle.net/wv3yopo0/2754/ - I remember some of the other things I tried were wrapping the results of the computed visibleColumns in observable, but of course that doesn't work because it's creating a _new_ observableArray each time computed is called. I also tried setting a pre-existing observable from inside the computed or from where the computed is referenced, but iirc that ran into the side effect error.

As for why I'm doing the caching that React and MobX should be handling, in my real use case of a virtualized list, there's significant up-front calculation that happens when rendering each row, but then the rows are static unless the columns are toggled. Now, you're saying that MobX should be preventing those rows from being re-rendered unless relevant props change, which is true, but the problem is that since the list is virtualized, those components are unmounted and then need to be re-rendered when scrolling back to their position. When I profiled it, this caching approach did significantly help the render time (but I'll be double-checking that in case I misunderstood or misremember something).

I had seen the side effect warning, but didn't realize it was due to this caching in the render. I'll look at that again, I can probably introduce an interstitial component to block an empty render, or do the work and caching in componentWillMount instead of from render. I'm actually still sort of confused about why MobX cares that this cache is being set from the render, since the cache isn't an observable and isn't used by anything else - it just sits until the next render cycle when it might be referenced. Is there a more detailed docs resource specifically about this side effects error?

**Comment by urugator** [comment]
> mistaken idea that a computed property was somehow magically observable to deeply nested components 

All derivations `render/computed/autorun/reaction` observe only things they directly access, because a modification of something which wasn't accessed, can't change the outcome of derivation.

> I had seen the side effect warning

That was probably something else... MobX would warn/throw only if the cache is observable. It's "forbiden" in general to modify state from within the render ... sure you can circumvent this by not making cache part of the state, but then you're breaking the rules (render must be a derivation of state/props only) and it's easy to introduce staleness (as you did).

> those components are unmounted

If it's neccessary to unmount the row (you can't just hide it) don't store "significant up-front calculation result" into the row component state, but to the list item model. You can use row component constructor or `componentWillMount` to initiate the calculation and table's component `componentWillUnmount` to dispose results stored to items if neccessary.
In case the rendering itself is expensive, you may consider placing the row rendering logic inside `computed`, it will cache the result (element) as long as computed is observed (check mobx-utils keepAlive), while staying reactive at the same time (and obviously rendering can't depend on props, but only on observables, same as with your cache array)...

**Comment by iabw** [comment]
Thanks for your help. Closing since there's no bug here.
