### ISSUE TITLE
Package size engines & dependency on the react-dom

### ISSUE THREAD

**Issue by GantMan** [mobxjs/mobx-react#479]
When checking package size on [bundlephobia](https://bundlephobia.com/result?p=mobx-react@5.1.2) I get the following error.

![image](https://user-images.githubusercontent.com/997157/40314397-fff5bfda-5cdd-11e8-9dae-6e244ad45172.png)

I also get an error when I try using the `package-size` module from npm
![image](https://user-images.githubusercontent.com/997157/40314428-129be3da-5cde-11e8-8655-1e333c302a10.png)

I understand this is probably dude to React Native, so you could consider setting an [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies)?   I'm not sure if that will work.

**Comment by mweststrate** [comment]
react-dom is not a (peer) dependency because it is only a dependency when using it in a DOM project, but not when using RN, etc.

If bundlephobia tries to resolve react-dom, it sounds like it is picking the wrong entry in the module in the first place, as the RN version doesn't `require('react-dom')`. Probably it doesn't respect this field in the package header? `  "react-native": "native.js",`

**Comment by mweststrate** [comment]
Closing for now, multiple packages would be neat, but the problem doesn't seem urgent enough to invest in it now.
