### ISSUE TITLE
Adding @observer to a class that extends a class already wrapped in @observer

### ISSUE THREAD

**Issue by skiritsis** [mobxjs/mobx-react#489]
When adding `@observer` to a class that extends a class already wrapped in `@observer` you get the following warning:
`Use `shouldComponentUpdate` in an `observer` based component breaks the behavior of `observer` and might lead to unexpected results. Manually implementing sCU should not be needed when using mobx-react. `

I understand that this change was made in version 5.1.0 as mentioned in changelog:
> Mobx-react will now print a warning when combining observer with a custom shouldComponentUpdate implementation. Fixes #417 

My question is, if this is a valid scenario that users should be warned about and can potentially lead to problems or is the warning is a false positive? The 2nd component detects the `sCU` implemented by the parent component and displays the warning(which will become an exception in future versions).

In my case both components implement the render method, and both of them are used in different parts of the application so both of them need the `@observer` wrapper.

Adding also a codepen [example](https://codesandbox.io/s/p59mj5n840) displaying the problem.

**Comment by urugator** [comment]
Use of inheritance is discouraged, if inavoidable for whatever reason, decorate only "leaf" classes. 
So in your case introduce non-decorated `AbstractHello` (making clear it shouldn't be instantiated on it's own) and decorated  `Hello1`, `Hello2` both extending from `AbstractHello`.
However I think you may still encounter all sort of issues, especially if parent class implements lifecycle methods. Consider using HoC, render callbacks etc instead.

**Comment by JabX** [comment]
I have the same issue and I already gave some thought about how to refactor the classes without inheritance, but in my case I'm pretty sure that it's the easiest way to proceed (derived class is a specialized version of the base class that overrides some of its behaviors and uses a lot of its state).

Anyway, looking at [this](https://github.com/mobxjs/mobx-react/blob/master/src/observer.js#L225) and how simple the "reactiveMixin" is, I don't think that there is any problem with subclassing observer components. The warning in question is even totally pointless because the SCU that's defined on the component is already the exact same function we're trying so set. So a very simple fix could be to add a `target.shouldComponentUpdate === reactiveMixin.shouldComponentUpdate` test before, so that we can continue subclassing our components in peace. Unless I'm missing something, of course.

**Comment by mweststrate** [comment]
Sounds like a sane fix indeed, PR with test and proposed change is welcome
:).

Op vr 1 jun. 2018 om 16:04 schreef Damien Frikha <notifications@github.com>:

**Comment by mweststrate** [comment]
Closing as MR above has been released
