### ISSUE TITLE
should i use observer for SFC? 

### ISSUE THREAD

**Issue by duhongjun** [mobxjs/mobx-react#511]
the parent component use inject and get some state from the store, and then pass the state as props to the child component(SFC), should i use @observer to decorate the child component ?

**Comment by urugator** [comment]
If component doesn't access any observables, then `observer` is redundant, however harmless, unless the component isn't pure. `observer` converts SFC to standard component class, therefore you won't benefit from any potential optimization performed by react due to a component being SFC (afaik there aren't any currently).

**Comment by duhongjun** [comment]
thanks
