### ISSUE TITLE
Using ext-react Container component with observer function throws Maximum call stack size exceeded

### ISSUE THREAD

**Issue by eucaos** [mobxjs/mobx-react#517]
When using an Ext-React Container component wrapped with the observer function i get :
"Uncaught RangeError: Maximum call stack size exceeded".

This is thrown from a baseClone method inside the lodash.clonedeepwith/index.js file.

Uncaught RangeError: Maximum call stack size exceeded
    at cloneSet (index.js:1056)
    at initCloneByTag (index.js:1300)
    at baseClone (index.js:877)
    at index.js:897
    at arrayEach (index.js:140)
    at baseClone (index.js:891)
    at index.js:897
    at arrayEach (index.js:140)
    at baseClone (index.js:891)
    at index.js:897

I'm using the latest mobx, mobx-state-treee and mobx-react libraries.

Usage ex:

```
import * as React from "react";
import { Container } from "@extjs/ext-react";
import { types } from "mobx-state-tree";
import { observer } from "mobx-react";
import { launch } from "@extjs/reactor";

const Todo = types.model({
  text: types.string
});

const store = Todo.create({ text: "324ewrfs" });

export const TodoComponent= observer(() => (
  <Container padding="20">
    {store.text}    
  </Container>
));
launch(<TodoComponent/>);
```

**Comment by mweststrate** [comment]
The attack doesn't show anything mobx related, please at least provide a
sandbox reproducing the issue, none of the methods mentioned in the stack
are shown in the code you listed...?

Op di 10 jul. 2018 09:51 schreef eucaos <notifications@github.com>:

**Comment by domehead100** [comment]
@eucaos, wherever you're passing an observable array to lodash, what happens if you call .splice() on it and pass the spliced version?

An observable array is not an actual array, which might be confusing lodash.

I feel like I've been seeing a couple of issues with forEach since we started using mobx 5.  In one case it seemed to be iterating over the same array element eternally until I got a stack overflow as you reported.  In another, a coworker told me she couldn't get forEach to iterate at all (a breakpoint in the callback never hit).  In both cases, .splice() worked around the problem for now.  Could be something we were doing wrong, but it wasn't obvious to me.  I think lodash was involved in one of these problems that we saw.

Not very helpful, I know.  If I get some time I'll try to reproduce.

**Comment by eucaos** [comment]
I tracked back the issue to an ExtJS cloneProps method which is using loadash cloneDeepWth function.

From ExtJS comments :
/**
         * Cloning props rather than passing them directly on as configs fixes issues where Ext JS mutates configs during
         * component initialization.  One example of this is grid columns get $initParent added when the grid initializes.
         * @param {Object} props
         * @private
         */

![image](https://user-images.githubusercontent.com/6533163/42557898-5d305222-84f8-11e8-9ad8-de0ec8ffb88a.png)

I created an issue with a simplified example (with only the observer function used) on the Ext-Reactor library https://github.com/sencha/extjs-reactor/issues/742.

Thanks for your answers !
