### ISSUE TITLE
make observer like autorun with breaking changes

### ISSUE THREAD

**Issue by worudso** [mobxjs/mobx-react#533]
https://github.com/ownerclan/mobx-react/tree/autorun-like
This fork is working now.

```typescript
export interface IObserverOptions {
    delay?: number
    name?: string
    scheduler?: (callback: () => void) => any
    onError?: (error: any) => void
}
```
```typescript
@observer({ delay: 100 }) 
class App extends React.Component {
    // ...
}
```

I want to know opinions before I proceed more.

First, do you guys agree that observer's interface should be like autorun?
Second, this will break the current interface, because there's no way for new `observer` to stay compatible with current `observer` that has optional arguments and works as both function and decorator. But passing store names to `observer` like `@observer(["store1", "store2"])` is deprecated(but it still works), so if it's ok not to support it anymore, then I think that new `observer` would be acceptable.

**Comment by mweststrate** [comment]
I think this is functionality that is necessarily needed in this package, but could be distributed as separate package as well? MobX-react now relies on the React scheduler it self and I think that in 98% of the cases that is clearer solution

Just curious, what caused the need for a mechanism like this?

**Comment by worudso** [comment]
@mweststrate Whay I needed was only debounce because of too frequent updates in my mobx store, so I first tried [react-debounce-renderer](https://www.npmjs.com/package/react-debounce-render), but it didn't work with mobx-react. And I read mobx-react implementation and I thought modifying `observer` is the only way to do what i wanted.

**Comment by worudso** [comment]
https://github.com/mobxjs/mobx-react/pull/541

**Comment by mweststrate** [comment]
@worudso could you elaborate on "I first tried react-debounce-renderer, but it didn't work with mobx-react.". What didn't work? I would expect that if you have a parent component that de-references the observables, and then passes them down to a plain component, wrapped with debounce, it would work .

My feeling currently is that this scenario is so rare that it doesn't justified to put it into mobx-react, especially since it can be expressed by composing existing solutions together (which is obviously not as simple as it would if it was in the package, but the tradeoff here is complicating the package and api)
