### ISSUE TITLE
How to define the shape of the observable array

### ISSUE THREAD

**Issue by WojciechKo** [mobxjs/mobx-react#536]
Hi!
I want to define the shape of the observable array, like it's possible in standard `prop-types`.
I've produced the following code but it doesn't validate the shape of the array. It doesn't produce any warning when elements of the array doesn't match the defined shape.
Any idea if I'm doing something wrong or this feature is not supported?

```javascript
import React, { Component } from 'react';
import { observer, PropTypes } from 'mobx-react';
import RealPropTypes from 'prop-types';

@observer
class List extends Component {
  static propTypes = {
    bets: PropTypes.observableArrayOf(
      RealPropTypes.shape({
        id: RealPropTypes.number
      })
    )
  }
}
```

**Comment by mweststrate** [comment]
if the objects in the observable array are observable objects (which is by
default the case) you should the exposed propTypes for observable objects
as well. If you don't want them to be observable, make sure to create a
shallow observable array instead of a deep observable array (see modifiers
in the documentation)

Op ma 27 aug. 2018 om 00:39 schreef Wojciech Korzeniowski <
notifications@github.com>:

**Comment by WojciechKo** [comment]
Thabks for reply!
If I understand correctly, I should use PropTypes from `mobx-react` instead of `prop-types`.
But still, I don't see any counterpart of the  `shape` from `prop-types` in the `mobx-react`.

**Comment by mweststrate** [comment]
I'm not sure whether `propTypes.shape` expects a non-primitive object? Best create a sandbox demonstrating the issue first, to make sure the error is not somewhere else. It is btw pretty simple to write your own type validators, they are pretty straightforward functions

**Comment by mweststrate** [comment]
Closing as question seems answered. Reopen if it aint
