### ISSUE TITLE
Question: Why should I use inject decorator?

### ISSUE THREAD

**Issue by BjornRombaut** [mobxjs/mobx-react#553]
I'm new to MobX and I'm wondering why I should use the inject decorator instead of directly using my stores. (I'm using typescript, but that doesn't affect anything). Both of the examples have the same result. I do understand that injecting stores in a 'Dependency Injection' kind of way improves testability, but this can also be done by mocking imports (https://jestjs.io/docs/en/es6-class-mocks). Am I missing something?

**With inject**
```typescript
import { inject, observer } from 'mobx-react';
import { RootStore } from '../../stores/root.store';
import { AppStore } from '../../stores/app.store';

interface MyComponentProps {
  appStore?: AppStore;
}

@inject((rootStore: RootStore) => ({
  appStore: rootStore.appStore,
}))
@observer
export class MyComponent extends React.Component<MyComponentProps> {
  public componentDidMount(): void {
    this.props.appStore!.setMessage('Hello world');
  }

  public render(): React.ReactNode {
    return <span>{this.props.appStore!.message}</span>
  }
}
```
I also have to pass the rootStore to the Provider
```jsx
<Provider {...rootStore}>
  <MyComponent />
</Provider>
```

**Without inject**
```typescript
import { observer } from 'mobx-react';
import { appStore } from '../../stores/app.store';

@observer
export class MyComponent extends React.Component {
  public componentDidMount(): void {
    appStore.setMessage('Hello world');
  }

  public render(): React.ReactNode {
    return <span>{appStore.message}</span>
  }
}
```
I don't have to create a rootStore, all stores are imported in the components that use them.

**Comment by urugator** [comment]
https://github.com/mobxjs/mobx-react/issues/410#issuecomment-388058128

**Comment by BjornRombaut** [comment]
@urugator If I understand it correctly the goal of the inject is to avoid usage of globals and doesn't have anything to do with mobx? For example, we could use provide and inject to share other globals like moment / lodash / ...? Sorry for the duplicate ticket, just trying to understand things correctly.

Thanks for the quick response.

**Comment by BjornRombaut** [comment]
I'll close this ticket due to duplicate.. My bad 😬

**Comment by urugator** [comment]
> other globals like moment / lodash / ...?

There is no problem with importing **stateless** things like classes, static functions (including lodash/moment), constants etc. That's how you're supposed to split the code, otherwise everything would have to be placed in single file.

> If I understand it correctly the goal of the inject is to avoid usage of globals

Last sentence in that comment: **"Also I would like to point out that context/providers (or any DI solution in general) is not an alternative to module imports, but an alternative to passing dependencies explicitely to constructor functions."**

Meaning that you usually don't use a global variables to pass the state around. You use local variables, function parameters and composition.
For example in react you use function `createElement` and passes the state via arguments called props. That's how you pass (statefull) dependencies by default. 
Sometimes passing state like this can be troublesome. For example when you have to pass the depedency transitively through multiple function calls. In react this is known as "prop drilling".
What you can do is to make all functions dependent on some common object called "context", instead of the individual variables. And ideally you will design it in a way that you don't have to pass this context object manually every time.
The context is still a runtime depedency provided at a call time (same as parameters or props)- therefore it can be swaped or modified, without the need to change the implementation of the consumers.

So no, it's not to avoid globals, because the use of globals was never the starting point.

It doesn't mean that you should replace your imports with context (Provider/Inject). It means, that you should start with passing dependencies via props and consider context only if it gets messy or hard to manage.

> doesn't have anything to do with mobx

It's just a wrapper around react's (old) context api, but yes you can use it for anything.   
It's not absolutely unrelated to mobx though, inject also accepts function, which is also reactive, check the docs for more info.
