### ISSUE TITLE
How to use observer components with lambda parameters

### ISSUE THREAD

**Issue by jtheisen** [mobxjs/mobx-react#625]
This isn't a bug report but rather a documentation suggestion or just an FYI.

I use lambdas in render methods a lot. That triggers re-rendering which often isn't that big of a deal. If it becomes a deal, you want to suppress re-rendering of certain components. When a component is an `@observer`, however, your have to do that with means other than overriding `shouldComponentUpdate`, as that's off the table.

(This is related to [this comment](https://github.com/mobxjs/mobx-react/issues/543#issuecomment-418992265) about why props themselves are observable. This ticket serves as a work-around in those cases where we don't want that.)

We define a trivial helper component that *isn't* an `@observer`:

```
export class Frozen extends React.Component<{ render: () => JSX.Element }> {
  shouldComponentUpdate() {
    return false
  }

  render() {
    return this.props.render()
  }
}
```

Then we can use an `@observer` component `SubComp` like this:

```
<Frozen render={() => <SubComp onFoo={() => { ... }} />} />
```

Since `Frozen`'s render method is never called twice, `onFoo` never changes and `SubComp` does not re-render gratuitoulsy.

[Here's a code sandbox](https://codesandbox.io/s/3r41ll97zp).

**Comment by urugator** [comment]
Callbacks props are convenient, but not trivial to optimize.
It's possible to easily introduce staleness if the callback isn't pure - which is often the case, because of avoiding prop drilling:
```javascript
const x = this.props.x;
<Frozen render={() => <SubComp thing={() => x} />} /> // SubComp won't update even if "x" changes
```
It's solvable with memoizing the callback:
[`useMemo` hook](https://reactjs.org/docs/hooks-reference.html#usememo):
```javascript
const x = this.props.x;
const thing = useMemo(() => () => x />, [x]); 
return <SubComp thing={thing}>
```
without hook:
```javascript
constructor() {
  this.thing = memoizeOne(({ x }) => () => x />);  
}
render() {
  const x = this.props.x;
  return <SubComp thing={this.thing({x})}>  
}
```
But it makes callback props less attractive and even potentially slower due to additional shallow equality checks.
So as always - don't optimize unless you really have to...

**Comment by jtheisen** [comment]
Didn't know about `useMemo`. `SubComp` will update on `x` changes if it's an `observer` and calls the callback on rendering though.

**Comment by urugator** [comment]
> SubComp will update on x changes if it's an observer and calls the callback on rendering though.

Only if `x` is observable (not a plain value) ... and since the value is "passed" as part of the clojure, there is no way to ensure/enforce this ...

**Comment by jtheisen** [comment]
Sure, but that's true even for the benign-looking `thing={this.something.x}`. (And I just realized your `x` wasn't an observable state member but a component prop - yeah, that won't work.) My solution does indeed depend on you having your stuff passed in be part of an observable state structure (if it returns something at all), but that should cover most cases for mobx users.

**Comment by jtheisen** [comment]
Yes, I agree with that one.

**Comment by mweststrate** [comment]
Closing, question seems answered

**Comment by jtheisen** [comment]
Did you expect me to close this?

**Comment by mweststrate** [comment]
You opened it, so if it is solved for you, it is solved :)

**Comment by jtheisen** [comment]
I didn‘t have a problem, I just made a suggestion.

**Comment by mweststrate** [comment]
ah sorry, missed that. People will find it here as well. I find it tricky to recommend as 'best practice', because it is easy to introduce bugs this way if people don't understand closures and thing thing it captures correctly, and if they do understand, it is easy to either hoist them or use one of the React mechanisms Reacts provides for that nowadays as @urugator suggested, and piggy-bag on that. 

Sorry if this came across as blunt. Was closing 50+ issues yesterday, and I definitely don't have time to read all the comments of all those issues again. So I closed it because it seemed an issue that stalled to a halt, without clear follow up point :). 

If you still would like to see something to this related to this in the docs, it is often easier to make a proposal in a PR, because PRs are often a bit more tangible on what idea  exactly you want to be sharing.

**Comment by jtheisen** [comment]
I'll keep it in mind.
