### ISSUE TITLE
Component does not re-render when I change state by MST

### ISSUE THREAD

**Issue by sxd1140** [mobxjs/mobx-react#633]
[![Edit antd reproduction template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w0964wm39w?expanddevtools=1)

Click `Move` button change `moving` in `Person Store`.

`<Spin>` will spin when `moving` is true.

I don't know this is about mobx-react or MST.

Help me plz.

**Comment by mweststrate** [comment]
The problem is that your render callback is not part of the App component,
and there for not an observer. You can fix that by extraction a component
and use that as render callback, or wrap the rendering in an Observer
section, as done here: https://codesandbox.io/s/qmzp6ww4w

Note that there are some react errors in your console.log as well

Op di 22 jan. 2019 om 11:35 schreef Sam Sun <notifications@github.com>:

**Comment by sxd1140** [comment]
Thanks a lot!
