### ISSUE TITLE
Does a reaction react to props which are not observable?

### ISSUE THREAD

**Issue by yoni-wibbitz** [mobxjs/mobx-react#657]
if I send through props a variable to a child component and in this child component I create a reaction which uses this variable as the data. will the reaction fire on changes? is this a good practice?

example
```
class Parent extends component {

   get size() {
       const {isVisible} = this.props; // Is visible is not observable
        return isVisible ? 100 : 0;
   } 

    render() {
        return <Child size={this.size} />
   }
}

class Child extends component {

   constructor(props) {
       super(props);
       reaction(()=> this.props.size, () => this.resizeFunc)
   } 

    render() {
        return <div ... />
   }
}
```

Thanks!

**Comment by mweststrate** [comment]
You have to put `observer` on Child, otherwise, this.prop will not be
observable.

**Comment by yoni-wibbitz** [comment]
`observer` will transform all of the props to be observables? even if their origin isnt observable?

**Comment by mweststrate** [comment]
No, it will just turn the this.props reference into an observable.

**Comment by yoni-wibbitz** [comment]
so, becuase this.props is observable the reaction makes deep comparison and it will see that this.props.size has changed and will trigger the effect function?

**Comment by mweststrate** [comment]
No, only shallow.

**Comment by yoni-wibbitz** [comment]
so the observer made this.props observable(and goes deep) on the whole this.props object and thats why reaction can react to this.props.size(it now observable because its inside this.props)?

**Comment by mweststrate** [comment]
No, shallow as stated.

Op di 12 mrt. 2019 16:31 schreef yoni-wibbitz <notifications@github.com>:

**Comment by mweststrate** [comment]
So to summarize (sorry for short answers, was on my phone before). The references of `this.props` and `this.props.x` are made observable by `observer`. But the _value_ of those props won't be made observable automatically, they will stay as they were provided by the parent component. So the observability is only shallow, not deep!

However, since passing new props from the parent will cause the `this.props.x` references to be updated, the reaction will react. 

So the reaction doesn't fire on the value of `isVisible` itself (which is a number, in other words, immutable and by definition not observable, even if we wanted to), but because `this.props.isVisible` get's reassigned when new props are provided by the parent.
