### ISSUE TITLE
"export 'useComputed' was not found in 'mobx-react'

### ISSUE THREAD

**Issue by jackple** [mobxjs/mobx-react#679]
After mobx-react@6.x, I still need to import useComputed from 'mobx-react-lite'?

**Comment by mweststrate** [comment]
`useComputed` has been deprecated already in lite, so we didn't bother to include it in the new mobx-react bindings. See https://github.com/mobxjs/mobx-react-lite#usecomputedfunc---t-inputs-readonlyarrayany---t for details

**Comment by jackple** [comment]
Thanks! 😄.

**Comment by jackple** [comment]
```
import { useLocalStore, useObserver } from 'mobx-react-lite'
```
I think import `useXXX` from `mobx-react-lite` is weird beacuse I did not install it by myself!!!

**Comment by mweststrate** [comment]
useLocalStore and useAsObservable source can be imported from mobx-react.
useObserver not (yet), as I don't see any clear benefit of it yet over
`observer` and `<Observer>`. It could tecnically be exposed as well without
any problem, I'm just not conviced yet that we should offer a third way of
introducing observability. I think it is would be just confusing.

Anyway, you could simply write your own `useObserver` (it's not exactly the
same but close enough): `const useObserver = fn =>
<Observer>{fn}</Observer>`.

If you would like to discuss useObserver further, please open a separate
issue since this one is about useComputed.

**Comment by jackple** [comment]
There is no `useLocalStore` or `useAsObservable` in `mobx-react.d.ts`

**Comment by mweststrate** [comment]
Ah good point, they are present though, the typings seem to be outdated
indeed, will fix

**Comment by mweststrate** [comment]
Fixed in 6.0.1

**Comment by jackple** [comment]
@mweststrate nothing changed!😄https://github.com/mobxjs/mobx-react/blob/master/src/index.d.ts

**Comment by mweststrate** [comment]
Lol, edited the wrong file,  6.0.2 it is then.

Op do 30 mei 2019 12:03 schreef jackple <notifications@github.com>:
