### ISSUE TITLE
✋Looking for maintainers

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-react#688]
I am looking for maintainers of this repository. That probably won't be too much of a burden (no big features in the planning), as it is mostly reviewing an occasional PR and releasing it. But there are some [funds](https://opencollective.com/mobx) available to compensate if it is gonna cost you too much time.

**Comment by taranovalexander** [comment]
Hi @marksilvis ! I am impressed with mobx, and every day I use it in my work. I'll be glad to help with maintaining this project

**Comment by FredyC** [comment]
@taranovalexander You got that name wrong :) Doesn't matter. You can start helping by responding to issues if you know the answer or reviewing PRs. The https://github.com/mobxjs/mobx repo probably needs it more than this one.

**Comment by lmaddio** [comment]
I would like to help also :)

**Comment by FredyC** [comment]
@lmaddio Same comment as I said above applies to you ;) Just help however you can, be active in a community or contribute to open PRs. There is no need for any sort of special badge or access to that.

**Comment by JunlinZhu-Tommy** [comment]
Same, I would like to help.

**Comment by FredyC** [comment]
You don't need to announce your intention, just be helpful as much as you can. We will notice, don't worry.

**Comment by mweststrate** [comment]
Awesome guys! Feel free to chime in issues or review PRs. Once you need more permissions, just let us know!

To get started, mobx-react(-lite) or mobx-utils might be slightly less overwhelming to start. 

 If you have experience with MST, make sure to check out that repo as well, as I think that is currently the repo where most questions are raised, and a lot of them are how-should-I-do-... questions.

**Comment by FredyC** [comment]
Sorry for my reluctance and cold approach here. In the past, there have been a couple of people who offered help but then complete silence for some reason. I am not sure if they were expecting permissions right away and when none were given they lost interest. I could be wrong for sure.

I am naturally careful because anonymous internet is kinda full of scammers. Call me a pessimist if you like, but I believe that for open-source projects like we should be extra careful about who gets access. People do trust it and they won't be double-checking if the next version does not come with some sort of malware until it's too late.

So I prefer if people show their intention first by being active and helping however they can without actual permissions. Asking for permission should have a good reason in my opinion.

**Comment by mweststrate** [comment]
Yes!

**Comment by ItamarShDev** [comment]
> Sorry for my reluctance and cold approach here. In the past, there have been a couple of people who offered help but then complete silence for some reason. I am not sure if they were expecting permissions right away and when none were given they lost interest. I could be wrong for sure.
> 
> I am naturally careful because anonymous internet is kinda full of scammers. Call me a pessimist if you like, but I believe that for open-source projects we should be extra careful about who gets access. People do trust it and they won't be double-checking if the next version does not come with some sort of malware until it's too late.
> 
> So I prefer if people show their intention first by being active and helping however they can without actual permissions. Asking for permission should have a good reason in my opinion.

As one of the ones who disappeared, I understand your view.

Just wanted to point out that i _do_ follow PRs and issue but reluctant to get into most of them because a lot changed in my life that took me away for being active in the community.
- I have a new job in a another city and still adjusting the long commutes
- i have a new baby that takes most of my evenings

So i am trying to gradually get back to be active in here, but after almost a year of low to none activity, it takes some time to get back on the horse


Sorry if I made you feel i wasn't into MobX by being inactive

**Comment by FredyC** [comment]
@ItamarShDev I certainly wasn't talking about you, not at all. Mostly about folks who stopped by to say they want to be maintainers and then did nothing. Don't worry, life changes always take priority.
