### ISSUE TITLE
As a much as it can Functional programming with React & Mobx

### ISSUE THREAD

**Issue by jmaguirrei** [mobxjs/mobx-react#69]
I am building a collaborative app and I am wondering if it's possible to have almost just pure functions with React & Mobx, that means, no React State at all (only mobx state) and as few as possible lifecycle methods from React (for example to scroll to the bottom of a list when the component is mounted/updated).

The purpose? Avoid unnecessary use of classes and state, performance boost, cleaner code and make the app portable in the future to other pure functional language (like Elm for example).

So, instead of having:

`class MyComponent extends React.Component ...`

Have

`const MyComponent = (someProps) => {}`

At facebook say that future performance improvements are coming if you use this pattern for your components.

The question: Does the `@observer` decorator (in my case I use `export default observer(MyComponent)` keep the component pure (if its defined as a const instead of a class) or it turns it into a class? It's possible to have pure functional programming using Mobx?

**Comment by mweststrate** [comment]
@jmaguirrei for simplicity `mobx-react` turns the components into classes. Until react really provides benefits performance wise for real functional components this is the simplest approach code was.

I noticed that the only reason to write class-like components is often having local state. Sometimes also (async) processing in component will mount, but that can often be abstracted away to stores easily. So I am thinking about introducing the following syntax to introduce local state:

`observer((props) => initialStateObject, (props, context, state) => rendering)`

That means that state can be captured in the closure of the render function (the third param) but the component can be written as function component, and the event handlers can be moved outside the component:

```javascript
const MyButton = observer(() =>  ({ clickCount: 0 }), (props, _, state) => (
   <div onClick={() => state.clickCount++}>{state.clickCount}</div>
))
```

and with event handlers extracted:

```javascript
const MyButton = observer(
  () =>  ({ clickCount: 0 }),
  (props, _, state) => <div onClick={() => buttonClick(state)}>{state.clickCount}</div>
)

function buttonClick(state) {
  state.clickCount++
}
```

It might be a nice way to write components. Or it might not add value at all :) 

N.B. note that context is the second argument to have the api similar to state_less_ function components

**Comment by capaj** [comment]
@mweststrate I like the idea. Only problem I have with it is this:

```javascript
observer((props) => initialStateObject, (props, context, state) => rendering)
```

I would prefer for the signature to be:
```javascript
observer((props) => initialStateObject, (props, state, context) => rendering)
```

Why? I simply never use context for anything in react. Why should I bother writing it out every time?

**Comment by EmilTholin** [comment]
I really like how that looks, and I agree with the comment from @capaj above. Will there be any performance differences from creating a class, or will it just be sugar for the following:

```js
const MyButton = observer(React.createClass({
  getInitialState: function() {
    return observable({
      clickCount: 0
    });
  },
  render: function() {
    let {state} = this;
    return <button onClick={() => ++state.clickCount}> {state.clickCount} </button>;
  }
}));
```
If it is just sugar, it might be confusing to introduce another observer pattern, since the one above lets you e.g. scroll to bottom on componentDidMount as mentioned by @jmaguirrei

**Comment by jmaguirrei** [comment]
@mweststrate 

> for simplicity mobx-react turns the components into classes. Until react really provides benefits performance wise for real functional components this is the simplest approach code was.

Questions:
1) That means that if React provides in the future better optimizations for stateless functional components, Mobx will no longer have to turn components into classes?
2) If not (still converting to classes), can we be confident there still be as performant as the new React optimization? (I know it's hard to say, but maybe you have an opinion)
3) Does Mobx implements its own shouldComponentUpdate under the hood?

I am a little lost now with the better architecture for React components, reading a lot and doing some tests.

It seems that having:
1) A container component that connects to data sources (I use Meteor/Mongo) and holds the state (Mobx/Redux) and pass the actions to the:
2) Presentational component that apply styles and render all the markup and just uses props.

It's a pattern to follow because both the separation of concerns and performance.

Is there any example / boilerplate with Mobx that follows that pattern? Anything with Meteor also?

Thanks!

**Comment by mweststrate** [comment]
@jmaguirrei 

1) depends much on the lifecycle behavior of these 'optimizations'. stateless function components never change, except when their props change(?). On the other hand observer components need to change if its observables change. But changing props is less likely from them (because with stateless function components the parent needs to rerender to pass in new props, which isn't the case for observer components). So the two scenario's are not entirely comparable.
2) similar answer; depends on your use case. If the point of your component is to never re-render, you don't have to observer in the first place. If your point is to re-render when data changes, this would not be a stateless function component when not using MobX. So MobX functional components are syntactically equal to React stateless function components, but in contrast to React stateless components, they are 'alive' and don't push the burden of invalidation to the parent.
3) yes, MobX implements shouldComponentUpdate, almost literally the same as `PureRenderMixin`

I think most people with MobX are less explicit about this separation. There are components that render 'models', which could be purely representational, depends a bit on where you put the event handlers. You can keep that separation strict or not based on your personal preferences. 

For meteor + mobx checkout https://github.com/markoshust/mantra-matui-mobx/ or maybe http://markshust.com/2016/06/02/creating-multi-page-form-using-mobx-meteor-react
