### ISSUE TITLE
What is MobXProviderContext?

### ISSUE THREAD

**Issue by bayoremit** [mobxjs/mobx-react#696]
Learning how to use mobx 6 with react's new context API and ran across **MobXProviderContext** being mentioned but there is no documentation on what it is and how it helps

Lil exert from the README in this project
> It is possible to read the stores provided by Provider using React.useContext, by using the MobXProviderContext context that can be imported from mobx-react.

The migration doc discusses using mobx in a hooks world, but nothing about using the new context api in a class component using contextType. I'm guessing **MobXProviderContext** might have something to do with that?

Thanks in advance

**Comment by urugator** [comment]
In V6, the implementation of `inject/Provider` uses new context instead of the legacy one.
`MobXProviderContext` is exposed so you can use `contextType` or `useContext` as an alternative to `inject`.
However if you're not using `inject/Provider` already, you can forget it exists and use the react's context api directly.

**Comment by FredyC** [comment]
Duplicate to #689

**Comment by bayoremit** [comment]
Thanks for the clarification guys
