### ISSUE TITLE
Inject does not work correctly with components that use React.forwardRef

### ISSUE THREAD

**Issue by vkrol** [mobxjs/mobx-react#717]
`inject` does not work correctly with components that use `React.forwardRef`. 
`isStateless` returns `true` for components that wrapped via `React.forwardRef` (https://github.com/mobxjs/mobx-react/blob/master/src/inject.js#L20) so `this.props.forwardRef` is not passed to these components.
```
const React = require("react");
const ReactDOM = require("react-dom");
const { inject, Provider } = require("mobx-react");

const e = React.createElement;

test("inject should work with components that use forwardRef", () => {
    const FancyComp = React.forwardRef((_, ref) => {
        return e("div", { ref });
    });
    
    const InjectedFancyComp = inject("bla")(FancyComp);
    const ref = React.createRef();
    
    ReactDOM.render(
        e(
            Provider,
            { bla: 42 },
            e(
                InjectedFancyComp,
                { ref },
                )
            ),
        document.createElement("div")
    );
    
    expect(ref.current).not.toBeNull(); // this assertion is failing
    expect(ref.current).toBeInstanceOf(HTMLDivElement);
});
```
Minimal reproducible example: https://github.com/vkrol/mobx-react-inject-forward-ref-bug

**Comment by FredyC** [comment]
Well, I think we should use [react-is](https://www.npmjs.com/package/react-is) to reliably detect these variants instead of inventing own.

**Comment by vkrol** [comment]
I am not sure that `react-is` has the complete solution to this problem. Probably we will have to invent our own solution on the basis of `react-is`.

In my opinion, `react-redux` has more bulletproof solution to the problem of ref forwarding. `connect` is not wrapping a passed component via `React.forwardRef`. A user is forced to pass the `forwardRef` flag to the `connect` function https://react-redux.js.org/api/connect#forwardref-boolean to do it.

**Comment by FredyC** [comment]
@vkrol Yea I kinda wanted to suggest to hide it under the flag as well but adding options object to the simplicity of `inject` does not feel right. What should be the default considering it does wrapping right now? Redux can afford it because they have many other options there and it makes sense.

Having it `false` by default introduces ugly gotcha. Single-use of such component which needs access to the ref and you are left stumbling in the dark. You have to look into docs to figure that there is an option for that and enabled it. I might be mistaken, but without that option, it would just silently fail and give you `null`, right?

That means it should be enabled by default and people can disable it if they are sure they don't need a ref. But it's not ideal either.

The react-is can at least detect if a component has `forwardRef` applied so we don't need to do that and avoid the issue.

---

Btw, this might be an additional reason why we consider [inject to be obsolete](https://mobx-react.js.org/recipes-inject). Migrating away from it solves many issues like that.

**Comment by vkrol** [comment]
In my opinion, it should be in the `options` object and the default value should be `false`. I think that this is very rarely used functionality.

**Comment by vkrol** [comment]
> The react-is can at least detect if a component has forwardRef applied so we don't need to do that and avoid the issue.
It is not very reliable solution because of `React.forwardRef` can be wrapped via `React.memo`:
```
const FancyComp = React.memo(React.forwardRef((props, ref) => <div ref={ref}/>));
```
I do not think that we can or should inspect these cases deeply.

**Comment by FredyC** [comment]
> This is the another argument in favor of abandoning automatic wrapping via `React.refForward` and shifting the responsibility for this to the user.

As I said, a major problem with that is a silent failure in case you want a ref from the component which is not configured that way. I agree it's not that often, but is it worth to confuse people with it? I don't think so. If we do it by default, then nobody will be surprised and if someone wants to micro-optimize, they can disable it.

I am thinking that failure with double (or more) wrapping with `forwardRef` should be considered a React bug and as such we shouldn't be solving it here. Can you possibly create an issue in React repo if it's not there yet?

**Comment by vkrol** [comment]
> As I said, a major problem with that is a silent failure in case you want a ref from the component which is not configured that way. I agree it's not that often, but is it worth to confuse people with it? I don't think so. If we do it by default, then nobody will be surprised and if someone wants to micro-optimize, they can disable it.

I disagree. If it is works for `react-redux` users why it will not work for `mobx-react` users?
In the previous versions of `mobx-react` users accessed to the wrapper component instance via `wrappedInstance` property and it was not a problem. 

> I am thinking that failure with double (or more) wrapping with forwardRef should be considered a React bug and as such we shouldn't be solving it here. Can you possibly create an issue in React repo if it's not there yet?

No, there is no bug in React. The problem lies not in the double application of `forwardRef`, but in the fact that we cannot reliable determine if the component passed in `inject` can accept `ref` or not.

**Comment by FredyC** [comment]
> cannot reliable determine if the component passed in `inject` can accept `ref` or not.

That's not really our concern and that's why `forwardRef` should be there by default to lift such burden from the user. What is the benefit of not having it there by default?

Anyway, I took your failing examples and made in CodeSandbox. With the current build of `inject` it is indeed broken. BUT at the moment we use the modified version which attaches ref even for functional components, it's working just fine. So what's the problem really? :)

https://codesandbox.io/s/broken-worker-coonx

**Comment by FredyC** [comment]
So unless you see some other problem there, let's close this, finish the #716 and get rid of the `isStateless` check. Let's not complicate this with some options. If anyone wants more control, they can always make their own version of "inject" because the Context is exposed.

**Comment by vkrol** [comment]
> BUT at the moment we use your modified version which attaches ref even for functional components, it's working just fine. So what's the problem really? :)

We cannot use this version of `inject` because it will generate the following warning for function components:
> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

So we HAVE TO apply `React.forwardRef` **conditionally** and the problem is in the correct **condition**.

**Comment by vkrol** [comment]
Yes, probably you are right and we can apply `React.forwardRef` without any condition and it will fix this problem. I will do it in that PR.

**Comment by FredyC** [comment]
Awesome. Can you also add the test case you drafted here in that PR? From what I could see, we test only against class components, so it would good to have that covered as well.

**Comment by vkrol** [comment]
Done https://github.com/mobxjs/mobx-react/pull/716. I will close this issue when this PR will be merged, if you do not mind.

**Comment by josteph** [comment]
@FredyC @vkrol is version `6.1.2` published on NPM yet?

**Comment by FredyC** [comment]
6.1.2 published
