### ISSUE TITLE
observer component not updating when being  exported directly

### ISSUE THREAD

**Issue by uriklar** [mobxjs/mobx-react#836]
See codesandbox:
https://codesandbox.io/s/mobx-bug-recreation-2rpmd

The sandbox has instructions on what the bug is and how to fix it. 

Thanks for the great work!

**Comment by mweststrate** [comment]
That is because `<LayoutBlock />` inside the `LayoutBlock` refers to that function itself, _before_ it is wrapped with `observer`. So only the exposed component is an `observer`, but not the recursively called one. I recommend to always go for `const X = observer(fn); export default X`. 
(Imho modules get better readable anyway if the exports are all defined in one block at the end of a file)

**Comment by uriklar** [comment]
Thanks for the detailed response!
