### ISSUE TITLE
Conditional useObserver hook

### ISSUE THREAD

**Issue by AjaxSolutions** [mobxjs/mobx-react#864]
This is a feature request.  I'm looking for a way to use the `useObserver` hook conditionally.

Depending on the state of my component, I'd like to be able to _suspend_ and then _resume_ the `useObserver` hook.

**Comment by FredyC** [comment]
No hooks can be used conditionally. Use `<Observer>` component for conditional reactivity.

**Comment by AjaxSolutions** [comment]
@FredyC This is what I had in mind.
https://twitter.com/DavidKPiano/status/1228700861024604160
Is there a way to use hooks such as the `useObserver` hook in a way similar to "subscribable" objects.
https://codesandbox.io/s/subscribable-context-e4j31

**Comment by FredyC** [comment]
Streams are obviously a whole different paradigm. Feel free to use those, but MobX is about declarative observability so you never have to doubt that component will be up to date. When you introduce conditionals and have a bug in there, it will be really hard to track down.

**Comment by AjaxSolutions** [comment]
OK, I'll close this ticket.

**Comment by mweststrate** [comment]
note that useObserver is already a subscription mechanism, and way way
smarter than any stream subscription, for example observables in unused
branches won't be subscribed to, whereas stream subscriptions are much more
coarse grained and dumber. So formulating the problem as generic as you do,
it sounds to me like you are asking for something that is _worse_ than
what you have currently with useObserver. Now I don't know your use case,
but make sure you are not asking for this based on a theoretical exercise,
but rather on measured performance. Otherwise by trying to pull some clever
trick might very well be making things worse, not better.

**Comment by AjaxSolutions** [comment]
Thank you for your answer @mweststrate .

> for example observables in unused
> branches won't be subscribed to

Could you please explain what you mean by "unused branches" and how they are handled?

**Comment by FredyC** [comment]
@AjaxSolutions I believe he means something like this. To be honest, I did not know about this either. That basically gives you ability for conditional observability.

https://codesandbox.io/s/angry-sunset-doer5?file=/src/App.js

_Note: initial 2 renders is normal, happens even if you comment out mutation_

**Comment by AjaxSolutions** [comment]
Every interesting.  Thank you for the codesandbox @FredyC .
